# Configurações do Banco PostgreSQL
spring.datasource.url=jdbc:postgresql://${RAILWAY_PROXY_DOMAIN}:${RAILWAY_PORT}/${PGDATABASE}?sslmode=require&user=${PGUSER}&password=${PGPASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.h2.console.enabled=false


api.security.token.secret=${JWT_SECRET}
